export const services = [
    {
        id: 1,
        name: "Classic Haircut",
        duration: "45 min",
        price: 35,
        description: "Professional cut and styling",
        image: "/images/classicHair.png",
    },
    {
        id: 2,
        name: "Beard Trim",
        duration: "30 min",
        price: 25,
        description: "Precision beard shaping and trim",
        image: "/images/beardTrim.png",
    },
    {
        id: 3,
        name: "Hair Wash & Style",
        duration: "60 min",
        price: 45,
        description: "Complete wash, condition and style",
        image: "/images/hairWash.png",
    },
    {
        id: 4,
        name: "Full Service Package",
        duration: "90 min",
        price: 75,
        description: "Haircut, wash, beard trim and styling",
        image: "/images/full-package.png",
    },
    {
        id: 5,
        name: "Hair Trim",
        duration: "60 min",
        price: 65,
        description: "Complete wash, trim",
        image: "/images/angelbaby.jpg",
    },
    {
        id: 6,
        name: "Caesar Cut",
        duration: "90 min",
        price: 105,
        description: "Haircut",
        image: "/images/hair.png",
    },
    {
        id: 7,
        name: "Beard Trim",
        duration: "30 min",
        price: 25,
        description: "Precision beard shaping and trim",
        image: "/images/beardTrim.png",
    },
    {
        id: 8,
        name: "Hair Wash & Style",
        duration: "60 min",
        price: 45,
        description: "Complete wash, condition and style",
        image: "/images/hairWash.png",
    },
]

